"""
Day 32: Fallback Edge — Fixed for Python 3.14 compatibility
"""
import os
from typing import TypedDict, Union

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

# ------------------------------------------------------------------
# 1. State
# ------------------------------------------------------------------
class AgentState(TypedDict):
    query: str
    category: str
    confidence: float
    selected_model: str
    response: str

# ------------------------------------------------------------------
# 2. Nodes
# ------------------------------------------------------------------
def classify_node(state: AgentState) -> AgentState:
    query = state["query"].lower()
    if any(k in query for k in ["python", "code", "bug", "error"]):
        return {**state, "category": "code", "confidence": 0.95}
    elif any(k in query for k in ["math", "calculate", "sum", "equation"]):
        return {**state, "category": "math", "confidence": 0.88}
    elif any(k in query for k in ["hello", "hi", "how are you"]):
        return {**state, "category": "general", "confidence": 0.92}
    else:
        return {**state, "category": "unknown", "confidence": 0.45}

def model_selection_node(state: AgentState) -> AgentState:
    model_map = {"code": "gpt-4", "math": "gpt-4", "general": "claude-haiku"}
    selected = model_map.get(state["category"], "fallback-model")
    return {**state, "selected_model": selected}

def fallback_node(state: AgentState) -> AgentState:
    return {
        **state,
        "selected_model": "fallback-model",
        "response": "I'm not confident I understand your request. Could you rephrase?",
    }

def generate_node(state: AgentState) -> AgentState:
    response = f"[Generated by {state['selected_model']}] Answer to: '{state['query']}'"
    return {**state, "response": response}

# ------------------------------------------------------------------
# 3. Fallback Edge — return plain strings, not Literal
# ------------------------------------------------------------------
def route_after_classification(state: AgentState) -> str:
    """
    Returns a plain string node name. LangGraph routes based on this.
    """
    confidence = state["confidence"]
    category = state["category"]
    
    if confidence < 0.7 or category == "unknown":
        print(f"⚠️  FALLBACK: confidence={confidence}, category={category}")
        return "fallback"
    
    print(f"✅ NORMAL: confidence={confidence}, category={category}")
    return "select_model"

# ------------------------------------------------------------------
# 4. Build graph
# ------------------------------------------------------------------
builder = StateGraph(AgentState)

builder.add_node("classify", classify_node)
builder.add_node("select_model", model_selection_node)
builder.add_node("fallback", fallback_node)
builder.add_node("generate", generate_node)

builder.set_entry_point("classify")

# Conditional edges — map return strings to node names
builder.add_conditional_edges(
    "classify",
    route_after_classification,
    {
        "select_model": "select_model",
        "fallback": "fallback",
    },
)

builder.add_edge("select_model", "generate")
builder.add_edge("fallback", "generate")
builder.add_edge("generate", END)

graph = builder.compile(checkpointer=MemorySaver())

# ------------------------------------------------------------------
# 5. Test
# ------------------------------------------------------------------
if __name__ == "__main__":
    tests = [
        "How do I fix a Python KeyError?",
        "What is the integral of x squared?",
        "Tell me about the color of dreams?",
        "Hi there!",
    ]
    
    for q in tests:
        print(f"\n{'='*50}")
        print(f"Query: {q}")
        print("-" * 50)
        
        result = graph.invoke(
            {"query": q, "category": "", "confidence": 0.0, 
             "selected_model": "", "response": ""},
            config={"configurable": {"thread_id": "day32"}},
        )
        
        print(f"→ Category: {result['category']}")
        print(f"→ Confidence: {result['confidence']}")
        print(f"→ Model: {result['selected_model']}")
        print(f"→ Response: {result['response']}")