services:
  - type: web
    name: ai-cost-optimizer-api
    runtime: docker
    repo: https://github.com/vanshx999/ai-cost-optimzer
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: web
    name: ai-cost-optimizer-dashboard
    runtime: node
    repo: https://github.com/vanshx999/ai-cost-optimzer
    buildCommand: npm install && npm run build
    startCommand: node server.js
    rootDir: frontend
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_URL
        sync: false
