services:
  - type: web
    name: ai-cost-optimizer-api
    runtime: docker
    repo: https://github.com/vanshx999/ai-cost-optimzer
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
